<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jon Minton">

<title>Modelling Country Effect IMR differences</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="main_notebook_files/libs/clipboard/clipboard.min.js"></script>
<script src="main_notebook_files/libs/quarto-html/quarto.js"></script>
<script src="main_notebook_files/libs/quarto-html/popper.min.js"></script>
<script src="main_notebook_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="main_notebook_files/libs/quarto-html/anchor.min.js"></script>
<link href="main_notebook_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="main_notebook_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="main_notebook_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="main_notebook_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="main_notebook_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Modelling Country Effect IMR differences</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jon Minton </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="aim" class="level2">
<h2 class="anchored" data-anchor-id="aim">Aim</h2>
<p>This document will show some possible strategies for modelling infant mortality trends over time and differences between populations</p>
</section>
<section id="preparation" class="level2">
<h2 class="anchored" data-anchor-id="preparation">Preparation</h2>
<p>First we need some data. I’ll take data from the Human Mortality Database</p>
<div class="cell" data-hash="main_notebook_cache/html/unnamed-chunk-1_9eb982f40cb6938e2269d42a0eba6d28">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(HMDHFDplus)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>HMDHFDplus<span class="sc">::</span><span class="fu">getHMDcountries</span>()</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>HMDHFDplus<span class="sc">::</span><span class="fu">getHMDitemavail</span>(<span class="st">"GBR_NP"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Countries of interest </span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">code =</span> <span class="fu">c</span>(</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"AUT"</span>, <span class="co">#Austria</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"BEL"</span>, <span class="co">#Belgium</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"FIN"</span>, <span class="co">#Finland</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"FRATNP"</span>, <span class="co">#France</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"DEUTNP"</span>, <span class="co">#Germany</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ITA"</span>, <span class="co">#Italy</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"NLD"</span>, <span class="co">#Netherlands</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"NOR"</span>, <span class="co">#Norway</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"POL"</span>, <span class="co">#Poland</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"SWE"</span>, <span class="co">#Sweden</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  <span class="st">"USA"</span>, <span class="co">#USA</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  <span class="st">"GBR_NP"</span> <span class="co">#UK</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span> </span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">death_tri =</span> <span class="fu">map</span>(</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>      code, </span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>      <span class="cf">function</span>(x) {</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>      HMDHFDplus<span class="sc">::</span><span class="fu">readHMDweb</span>(x, <span class="st">"Deaths_lexis"</span>, </span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>         <span class="at">username =</span> <span class="fu">Sys.getenv</span>(<span class="st">"HMD_USERNAME"</span>), </span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>         <span class="at">password =</span> <span class="fu">Sys.getenv</span>(<span class="st">"HMD_PASSWORD"</span>)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>      ) <span class="sc">|&gt;</span> </span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>          <span class="fu">filter</span>(Age <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>          <span class="fu">arrange</span>(Cohort) <span class="sc">%&gt;%</span> </span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>          <span class="fu">set_names</span>(<span class="at">nm =</span> <span class="fu">tolower</span>(<span class="fu">names</span>(.))) <span class="sc">|&gt;</span> </span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>          <span class="fu">select</span>(<span class="sc">-</span>openinterval) <span class="sc">|&gt;</span> </span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>          <span class="fu">pivot_longer</span>(</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>            <span class="at">cols =</span> female<span class="sc">:</span>total, </span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>            <span class="at">names_to =</span> <span class="st">"sex"</span>, </span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>            <span class="at">values_to  =</span> <span class="st">"deaths"</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>          )    </span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>      }</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>    <span class="at">expos_tri =</span> <span class="fu">map</span>(</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>      code, </span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>      <span class="cf">function</span>(x) {</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>      HMDHFDplus<span class="sc">::</span><span class="fu">readHMDweb</span>(x, <span class="st">"Exposures_lexis"</span>,</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>         <span class="at">username =</span> <span class="fu">Sys.getenv</span>(<span class="st">"HMD_USERNAME"</span>),</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>         <span class="at">password =</span> <span class="fu">Sys.getenv</span>(<span class="st">"HMD_PASSWORD"</span>)</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>     ) <span class="sc">|&gt;</span> </span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>          <span class="fu">filter</span>(Age <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>          <span class="fu">arrange</span>(Cohort) <span class="sc">%&gt;%</span> </span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>          <span class="fu">set_names</span>(<span class="at">nm =</span> <span class="fu">tolower</span>(<span class="fu">names</span>(.))) <span class="sc">|&gt;</span> </span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>          <span class="fu">select</span>(<span class="sc">-</span>openinterval) <span class="sc">|&gt;</span> </span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>          <span class="fu">pivot_longer</span>(</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>            <span class="at">cols =</span> female<span class="sc">:</span>total, </span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>            <span class="at">names_to =</span> <span class="st">"sex"</span>, </span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>            <span class="at">values_to  =</span> <span class="st">"exposures"</span></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>          )         </span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>tidy_df <span class="ot">&lt;-</span> </span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">|&gt;</span> </span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(code, death_tri) <span class="sc">|&gt;</span> </span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>    <span class="fu">unnest</span>(death_tri) <span class="sc">|&gt;</span> </span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>    <span class="fu">inner_join</span>(</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>      df <span class="sc">|&gt;</span> </span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>        <span class="fu">select</span>(code, expos_tri) <span class="sc">|&gt;</span> </span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>        <span class="fu">unnest</span>(expos_tri)) <span class="sc">|&gt;</span> </span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(year <span class="sc">&gt;=</span> cohort) <span class="sc">|&gt;</span> </span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>      <span class="at">tri_type =</span> <span class="fu">ifelse</span>(cohort <span class="sc">==</span> year, <span class="st">"lower"</span>, <span class="st">"upper"</span>)</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>    ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The above uses the HMDHFDPlus package to load data directly from the Human Mortality Database. Unfortunately this works some of the time but not all of the time.</p>
<p>So let’s do the Blue Peter thing and load the dataset we created earlier</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>tidy_df <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/tidy_df.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I’m not sure, but think it’s worth trying to sum up deaths and exposures by cohort to produce lexis parallelograms</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>lx_par_df <span class="ot">&lt;-</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  tidy_df <span class="sc">|&gt;</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(code, cohort, sex) <span class="sc">|&gt;</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">reframe</span>(</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">deaths =</span> deaths[tri_type<span class="sc">==</span><span class="st">'lower'</span>] <span class="sc">+</span> deaths[tri_type <span class="sc">==</span> <span class="st">'upper'</span>],</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">exposures =</span> exposures[tri_type <span class="sc">==</span> <span class="st">'lower'</span>] <span class="sc">+</span> exposures[tri_type <span class="sc">==</span> <span class="st">'upper'</span>]</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="descriptive-plots" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-plots">Descriptive plots</h2>
<p>Let’s look at how IMR varies over time by country</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>lx_par_df <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">imr =</span> deaths <span class="sc">/</span> exposures</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> cohort, <span class="at">y =</span> imr)) <span class="sc">+</span> </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span> </span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>() <span class="sc">+</span> </span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Birth cohort"</span>, <span class="at">y =</span> <span class="st">"Infant Mortality Rate (Log scale)"</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"IMR for selected countries"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 18 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="main_notebook_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We should maybe focus on post 1970, and look at sex separately.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>lx_par_df <span class="sc">|&gt;</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">imr =</span> deaths <span class="sc">/</span> exposures</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sex <span class="sc">!=</span> <span class="st">'total'</span>) <span class="sc">|&gt;</span> </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(cohort <span class="sc">&gt;=</span> <span class="dv">1970</span>) <span class="sc">|&gt;</span> </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> cohort, <span class="at">y =</span> imr, <span class="at">group =</span> <span class="fu">paste0</span>(code, sex), <span class="at">colour =</span> sex)) <span class="sc">+</span> </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>() <span class="sc">+</span> </span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>code) <span class="sc">+</span> </span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Birth cohort"</span>, <span class="at">y =</span> <span class="st">"Infant Mortality Rate (Log scale)"</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"IMR for selected countries"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="main_notebook_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>So, in log space, for each country, male IMRs look like female IMRs, but shifted up by a given amount.</p>
<p>This given amount looks similar for all countries. This is a simplifying assumption we can make.</p>
<p>Another simplifying/stylising assumption we can make is that mortality trends over time is log linear. Country effects then further adjust upwards or downwards from this general trend. (This are simply assumptions we can then develop further and critique afterwards. But they’re reasonable starting places.)</p>
<p>We can select a reference country. I think this should be Norway (and aspirational reference country!).</p>
</section>
<section id="modelling-and-model-predictions" class="level2">
<h2 class="anchored" data-anchor-id="modelling-and-model-predictions">Modelling and model predictions</h2>
<section id="running-linear-regression-models" class="level3">
<h3 class="anchored" data-anchor-id="running-linear-regression-models">Running linear regression models</h3>
<p>We can start with simple linear regression</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>training_data <span class="ot">&lt;-</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  lx_par_df <span class="sc">|&gt;</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">imr =</span> deaths <span class="sc">/</span> exposures</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sex <span class="sc">!=</span> <span class="st">'total'</span>) <span class="sc">|&gt;</span> </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(cohort <span class="sc">&gt;=</span> <span class="dv">1970</span>) <span class="sc">|&gt;</span> </span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">yrs_since_1970 =</span> cohort <span class="sc">-</span> <span class="dv">1970</span>) <span class="sc">|&gt;</span> </span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">code =</span> <span class="fu">factor</span>(code)) <span class="sc">|&gt;</span> </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">code =</span> <span class="fu">relevel</span>(code, <span class="st">"NOR"</span>))</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co"># First model: only time matters</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>mod_00 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(imr) <span class="sc">~</span> yrs_since_1970, </span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> training_data)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Second model: sex also matters </span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>mod_01 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(imr) <span class="sc">~</span> yrs_since_1970 <span class="sc">+</span> sex, </span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> training_data)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Third model: country also matters</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>mod_02 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(imr) <span class="sc">~</span> yrs_since_1970 <span class="sc">+</span> sex <span class="sc">+</span> code, </span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> training_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="comparing-models" class="level3">
<h3 class="anchored" data-anchor-id="comparing-models">Comparing models</h3>
<p>Each of the above models is more complex (parameterised) than the last. We can test whether the greater complexity is justified using F-tests (via ANOVA) and using something like BIC and AIC</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_00, mod_01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: log(imr) ~ yrs_since_1970
Model 2: log(imr) ~ yrs_since_1970 + sex
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1   1176 139.76                                  
2   1175 124.64  1    15.117 142.51 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Significantly better going from model 00 to model 01</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_01, mod_02)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: log(imr) ~ yrs_since_1970 + sex
Model 2: log(imr) ~ yrs_since_1970 + sex + code
  Res.Df     RSS Df Sum of Sq      F    Pr(&gt;F)    
1   1175 124.642                                  
2   1164  34.061 11    90.581 281.41 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Significantly better going from model 01 to model 02</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mod_00, mod_01, mod_02)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       df       AIC
mod_00  3  837.9330
mod_01  4  705.0831
mod_02 15 -801.1207</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mod 02 much better than the other two models</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(mod_00, mod_01, mod_02)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       df       BIC
mod_00  3  853.1477
mod_01  4  725.3694
mod_02 15 -725.0471</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mod 02 much better than the other two models</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The above all indicate country effects should be included.</p>
</section>
<section id="interpreting-model-output" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-model-output">Interpreting model output</h3>
<p>The best of the three models has the following summary output</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_02)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(imr) ~ yrs_since_1970 + sex + code, data = training_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.46509 -0.11908 -0.01855  0.10214  0.52216 

Coefficients:
                 Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)    -4.5093895  0.0195899 -230.190  &lt; 2e-16 ***
yrs_since_1970 -0.0376992  0.0003454 -109.162  &lt; 2e-16 ***
sexmale         0.2265635  0.0099681   22.729  &lt; 2e-16 ***
codeAUT         0.3460287  0.0240880   14.365  &lt; 2e-16 ***
codeBEL         0.3316310  0.0237221   13.980  &lt; 2e-16 ***
codeDEUTNP      0.2018375  0.0279058    7.233 8.56e-13 ***
codeFIN        -0.1029358  0.0237221   -4.339 1.55e-05 ***
codeFRATNP      0.2476061  0.0238387   10.387  &lt; 2e-16 ***
codeGBR_NP      0.3874066  0.0239606   16.168  &lt; 2e-16 ***
codeITA         0.3610769  0.0239606   15.070  &lt; 2e-16 ***
codeNLD         0.2029796  0.0238387    8.515  &lt; 2e-16 ***
codePOL         0.8997065  0.0240880   37.351  &lt; 2e-16 ***
codeSWE        -0.0955273  0.0237221   -4.027 6.02e-05 ***
codeUSA         0.6143548  0.0238387   25.771  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1711 on 1164 degrees of freedom
Multiple R-squared:  0.9332,    Adjusted R-squared:  0.9324 
F-statistic:  1250 on 13 and 1164 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The model predicts that, each year, log IMR falls by -0.0376992. The exponent of this is 0.9630026, so on average each year IMR falls by about 3.7% compared with the previous year.</p>
<p><strong>Note: To test for slowdown, include additional time-related terms, such as whether the year is 2012 or after. Then use ANOVA/AIC/BIC to see if the additional term is justified by better fit.</strong></p>
<p>Similarly, the exponents of the sex and country terms indicate what % higher or lower male IMR is than female, and how much higher it is in specific countries compared with Norway.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>implied_hazard_shifts <span class="ot">&lt;-</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(mod_02) <span class="sc">|&gt;</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="fu">str_detect</span>(term, <span class="st">"code|sex"</span>) ) <span class="sc">|&gt;</span> </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">term =</span> <span class="fu">str_remove</span>(term, <span class="st">"sex"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">term =</span> <span class="fu">str_remove</span>(term, <span class="st">"code"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(term, estimate) <span class="sc">|&gt;</span> </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">hazard_shift =</span> <span class="fu">exp</span>(estimate)) <span class="sc">|&gt;</span> </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(hazard_shift)) </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>implied_hazard_shifts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
   term   estimate hazard_shift
   &lt;chr&gt;     &lt;dbl&gt;        &lt;dbl&gt;
 1 POL      0.900         2.46 
 2 USA      0.614         1.85 
 3 GBR_NP   0.387         1.47 
 4 ITA      0.361         1.43 
 5 AUT      0.346         1.41 
 6 BEL      0.332         1.39 
 7 FRATNP   0.248         1.28 
 8 male     0.227         1.25 
 9 NLD      0.203         1.23 
10 DEUTNP   0.202         1.22 
11 SWE     -0.0955        0.909
12 FIN     -0.103         0.902</code></pre>
</div>
</div>
<p>Over this time period, IMRs in Poland are on average 146% higher (100 * (2.46 - 1)) than for the reference country, Norway. The next highest increased risk is living in the USA, where the IMR risks are 85% higher then in Norway, then in the UK (GBR_NP), where the risks are 47% higher. Only Sweden and Finland have lower IMR risks then Norway, with IMR risks around 9-10% lower.</p>
<p>For comparison, the male IMR is on average higher 25% than the corresponding female IMR.</p>
</section>
<section id="examples-of-more-complex-models-e.g.-to-test-austerity-hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="examples-of-more-complex-models-e.g.-to-test-austerity-hypotheses">Examples of more complex models (e.g.&nbsp;to test Austerity hypotheses)</h3>
<p>We can consider specifications that ‘flag’ years after 2012 as different from previous years. We can also look at specifications where these flags apply differently by countries.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>mod_03 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(imr) <span class="sc">~</span> yrs_since_1970 <span class="sc">+</span> sex <span class="sc">+</span> code <span class="sc">+</span> post_2012, </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>             <span class="co">#post_2012 is our 'flag'</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> training_data <span class="sc">|&gt;</span> </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>               <span class="fu">mutate</span>(<span class="at">post_2012 =</span> cohort <span class="sc">&gt;=</span> <span class="dv">2012</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>          )</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>mod_04 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(imr) <span class="sc">~</span> yrs_since_1970 <span class="sc">+</span> sex <span class="sc">+</span> code <span class="sc">*</span> post_2012, </span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>             <span class="co">#post_2012 is our 'flag'. The * after code means it interacts with country (i.e. is experienced differently in) different countries</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> training_data <span class="sc">|&gt;</span> </span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>               <span class="fu">mutate</span>(<span class="at">post_2012 =</span> cohort <span class="sc">&gt;=</span> <span class="dv">2012</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>             <span class="co"># n.b. we can just about use cohort as year as looking at IMR</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>          )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can compare these models using the same strategy as before:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_02, mod_03)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: log(imr) ~ yrs_since_1970 + sex + code
Model 2: log(imr) ~ yrs_since_1970 + sex + code + post_2012
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1   1164 34.061                                  
2   1163 29.523  1    4.5384 178.78 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># significantly better</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_03, mod_04)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: log(imr) ~ yrs_since_1970 + sex + code + post_2012
Model 2: log(imr) ~ yrs_since_1970 + sex + code * post_2012
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1   1163 29.523                                  
2   1152 22.415 11    7.1083 33.212 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># also significnatly better </span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mod_00, mod_01, mod_02, mod_03, mod_04)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       df        AIC
mod_00  3   837.9330
mod_01  4   705.0831
mod_02 15  -801.1207
mod_03 16  -967.5715
mod_04 27 -1270.0583</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(mod_00, mod_01, mod_02, mod_03, mod_04)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       df        BIC
mod_00  3   853.1477
mod_01  4   725.3694
mod_02 15  -725.0471
mod_03 16  -886.4263
mod_04 27 -1133.1258</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The most complex also preferred</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_04)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(imr) ~ yrs_since_1970 + sex + code * post_2012, 
    data = mutate(training_data, post_2012 = cohort &gt;= 2012))

Residuals:
     Min       1Q   Median       3Q      Max 
-0.45053 -0.08771 -0.00708  0.08331  0.43355 

Coefficients:
                           Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)              -4.4366654  0.0175218 -253.208  &lt; 2e-16 ***
yrs_since_1970           -0.0414092  0.0003743 -110.642  &lt; 2e-16 ***
sexmale                   0.2265635  0.0081282   27.874  &lt; 2e-16 ***
codeAUT                   0.3589119  0.0215235   16.675  &lt; 2e-16 ***
codeBEL                   0.3070072  0.0215235   14.264  &lt; 2e-16 ***
codeDEUTNP                0.1783128  0.0262268    6.799 1.69e-11 ***
codeFIN                  -0.0990956  0.0215235   -4.604 4.60e-06 ***
codeFRATNP                0.1953260  0.0215235    9.075  &lt; 2e-16 ***
codeGBR_NP                0.3576237  0.0215235   16.615  &lt; 2e-16 ***
codeITA                   0.3864829  0.0215235   17.956  &lt; 2e-16 ***
codeNLD                   0.1444401  0.0215235    6.711 3.03e-11 ***
codePOL                   0.9476619  0.0215235   44.029  &lt; 2e-16 ***
codeSWE                  -0.1280075  0.0215235   -5.947 3.61e-09 ***
codeUSA                   0.5409430  0.0215235   25.133  &lt; 2e-16 ***
post_2012TRUE             0.1137773  0.0360440    3.157 0.001638 ** 
codeAUT:post_2012TRUE    -0.0897526  0.0531622   -1.688 0.091628 .  
codeBEL:post_2012TRUE     0.1280435  0.0490812    2.609 0.009203 ** 
codeDEUTNP:post_2012TRUE  0.1817031  0.0536628    3.386 0.000733 ***
codeFIN:post_2012TRUE    -0.0199693  0.0490812   -0.407 0.684184    
codeFRATNP:post_2012TRUE  0.2959535  0.0501707    5.899 4.80e-09 ***
codeGBR_NP:post_2012TRUE  0.1859303  0.0515007    3.610 0.000319 ***
codeITA:post_2012TRUE    -0.1590001  0.0515007   -3.087 0.002068 ** 
codeNLD:post_2012TRUE     0.3314227  0.0501707    6.606 6.02e-11 ***
codePOL:post_2012TRUE    -0.3352580  0.0531622   -6.306 4.06e-10 ***
codeSWE:post_2012TRUE     0.1688973  0.0490812    3.441 0.000600 ***
codeUSA:post_2012TRUE     0.4156994  0.0501707    8.286 3.23e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1395 on 1152 degrees of freedom
Multiple R-squared:  0.956, Adjusted R-squared:  0.9551 
F-statistic:  1001 on 25 and 1152 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Because of the presence of interaction terms, the coefficients are now somewhat harder to interpret directly. Instead, we can look at the predicted values they imply, and how they differ between countries.</p>
</section>
<section id="showing-what-a-model-specification-predicts" class="level3">
<h3 class="anchored" data-anchor-id="showing-what-a-model-specification-predicts">Showing what a model specification predicts</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>pred_df <span class="ot">&lt;-</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_grid</span>(</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">cohort =</span> <span class="dv">1990</span><span class="sc">:</span><span class="dv">2022</span>, </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex =</span> <span class="fu">c</span>(<span class="st">"male"</span>, <span class="st">"female"</span>),</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">code =</span> <span class="fu">c</span>(</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"AUT"</span>, <span class="co">#Austria</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"BEL"</span>, <span class="co">#Belgium</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"FIN"</span>, <span class="co">#Finland</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"FRATNP"</span>, <span class="co">#France</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"DEUTNP"</span>, <span class="co">#Germany</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"ITA"</span>, <span class="co">#Italy</span></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"NLD"</span>, <span class="co">#Netherlands</span></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"NOR"</span>, <span class="co">#Norway</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"POL"</span>, <span class="co">#Poland</span></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SWE"</span>, <span class="co">#Sweden</span></span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"USA"</span>, <span class="co">#USA</span></span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"GBR_NP"</span> <span class="co">#UK</span></span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>  )  <span class="sc">|&gt;</span> </span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">yrs_since_1970 =</span> cohort <span class="sc">-</span> <span class="dv">1970</span>,</span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">post_2012 =</span> cohort <span class="sc">&gt;=</span> <span class="dv">2012</span></span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a>preds <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod_04, <span class="at">newdata =</span> pred_df)</span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a>preds_pred_df <span class="ot">&lt;-</span> </span>
<span id="cb35-28"><a href="#cb35-28" aria-hidden="true" tabindex="-1"></a>  pred_df <span class="sc">|&gt;</span> </span>
<span id="cb35-29"><a href="#cb35-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb35-30"><a href="#cb35-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred_limr =</span> preds</span>
<span id="cb35-31"><a href="#cb35-31" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now to visualise</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>preds_pred_df <span class="sc">|&gt;</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(training_data) <span class="sc">|&gt;</span> </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">obs_limr =</span> <span class="fu">log</span>(imr)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> cohort, <span class="at">color =</span> sex)) <span class="sc">+</span> </span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> obs_limr)) <span class="sc">+</span> </span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> pred_limr)) <span class="sc">+</span> </span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>code) <span class="sc">+</span> </span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Birth cohort"</span>, </span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Log IMR"</span>,</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Observed and predicted Log IMR for selected countries"</span>,</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Points: Observed. Lines: Predicted"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Joining with `by = join_by(cohort, sex, code, yrs_since_1970)`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 54 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="main_notebook_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The lines showing the model predictions show the importance of structural assumptions in the model. The model assumes a constant annual rate of mortality improvement throughout the whole series, and then allows the line over time to be moved upwards or downwards in log space for 2012 onwards.</p>
</section>
<section id="deciding-whether-a-more-complex-model-is-worth-its-additional-complexity" class="level3">
<h3 class="anchored" data-anchor-id="deciding-whether-a-more-complex-model-is-worth-its-additional-complexity">Deciding whether a more complex model is worth its additional complexity</h3>
<p>For countries where there has been slowdown after around 2012, this structural assumption might not be appropriate. Instead we should consider models in which the rate of improvement over time itself is allowed to be different after 2012 than before. As before we can build this model specification and compared the penalised fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>mod_05 <span class="ot">&lt;-</span>  <span class="fu">lm</span>(<span class="fu">log</span>(imr) <span class="sc">~</span> yrs_since_1970 <span class="sc">+</span> sex <span class="sc">+</span> code <span class="sc">*</span> yrs_since_2012, </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>              <span class="co">#Now using yrs_since_2012, which allows change in slope not just intercept</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> training_data <span class="sc">|&gt;</span> </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>               <span class="fu">mutate</span>(</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">post_2012 =</span> cohort <span class="sc">&gt;=</span> <span class="dv">2012</span>,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">yrs_since_2012 =</span> <span class="fu">ifelse</span>(</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>                   post_2012, </span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>                   cohort <span class="sc">-</span> <span class="dv">2012</span>,</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>                   <span class="dv">0</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>                  )</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>                 )</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>             <span class="co"># n.b. we can just about use cohort as year as looking at IMR</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>          )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Compare the models</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  mod_00, mod_01, mod_02, mod_03, mod_04, mod_05</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       df        AIC
mod_00  3   837.9330
mod_01  4   705.0831
mod_02 15  -801.1207
mod_03 16  -967.5715
mod_04 27 -1270.0583
mod_05 27 -1210.8527</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  mod_00, mod_01, mod_02, mod_03, mod_04, mod_05</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       df        BIC
mod_00  3   853.1477
mod_01  4   725.3694
mod_02 15  -725.0471
mod_03 16  -886.4263
mod_04 27 -1133.1258
mod_05 27 -1073.9203</code></pre>
</div>
</div>
<p>The model allowing a different slope for post 2012 doesn’t outperform the simpler model which simply adjusts the trend upwards or downwards. This suggests that the simpler model may be ‘good enough’ for producing summary estimates of how large any post 2012 slowdown may have been in IMR trends for different countries, even though it’s qualitatively not quite the pattern we see in the data.</p>
<p>Further model specifications, representing different theories about these trends and how they differ between places, can also be tried. In particular models including one or more breakpoints in the IMR trends may be worth looking at, as in <a href="https://www.dannydorling.org/wp-content/files/dannydorling_publication_id9575.pdf">this paper</a>. (i.e.&nbsp;the code in that paper, which looks at <span class="math inline">\(e_0\)</span> and <span class="math inline">\(e_{65}\)</span>, could also be applied to IMR trends as well.)</p>
</section>
<section id="summarising-the-good-enough-model" class="level3">
<h3 class="anchored" data-anchor-id="summarising-the-good-enough-model">Summarising the ‘good enough’ model</h3>
<p>Model 04, which is structurally overly ‘stylised’ (i.e.&nbsp;doesn’t look right) but still preferred over the more complex model 05, allows for single summary estimates of what’s happened to IMR trends post 2012. Or more specifically by what % earlier trends were ‘set back’ compared with the pre 2012 period.</p>
<p>As Norway is the reference category, we know the coefficient <code>post_2012TRUE</code> corresponds to Norway. This coefficient is about 0.0114. The exponent of this is 1.12, so around a 12% higher IMR for Norway compared with the pre 2012 trend.</p>
<p>For other countries, the <code>post_2012TRUE</code> coefficient needs to be added to the country-specific coefficient (e.g.&nbsp;<code>post_2012TRUE + codeGBR_NP:post_2012TRUE</code> for the UK), before exponentiating.</p>
<p>For the UK the estimate of how much IMRs were set back from 2012 onwards is <code>exp(0.1137773 + 0.1859303)</code> , which is 1.349, suggesting that from 2012 IMRs were around 35% higher than the long-term trend.</p>
<p>The following code shows the same for all other countries</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(mod_04) <span class="sc">|&gt;</span> </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(term, <span class="st">"post_2012"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">code =</span> <span class="fu">str_remove</span>(term, <span class="st">"post_2012TRUE"</span>),</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">code =</span> <span class="fu">str_remove</span>(code, <span class="st">"code"</span>),</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">code =</span> <span class="fu">str_remove</span>(code, <span class="st">":"</span>),</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">code =</span> <span class="fu">ifelse</span>(code <span class="sc">==</span> <span class="st">""</span>, <span class="st">"NOR"</span>, code)</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">delta =</span> <span class="fu">ifelse</span>(</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>      code <span class="sc">==</span> <span class="st">"NOR"</span>, </span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>      estimate,</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>      estimate <span class="sc">+</span> estimate[code <span class="sc">==</span> <span class="st">"NOR"</span>]</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_change =</span> <span class="fu">exp</span>(delta) </span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(code, pct_change) <span class="sc">|&gt;</span> </span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pct_change))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   code   pct_change
   &lt;chr&gt;       &lt;dbl&gt;
 1 USA         1.70 
 2 NLD         1.56 
 3 FRATNP      1.51 
 4 GBR_NP      1.35 
 5 DEUTNP      1.34 
 6 SWE         1.33 
 7 BEL         1.27 
 8 NOR         1.12 
 9 FIN         1.10 
10 AUT         1.02 
11 ITA         0.956
12 POL         0.801</code></pre>
</div>
</div>
<p>This suggests that the post 2012 period is associated with substantial setbacks in IMR in almost all countries included, with the exception of Italy and Poland. The USA has the highest rate of ‘setback’ relative to earlier trends, with IMR estimated to be around 70% higher than if there had not been a setback from 2012.</p>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>This notebook includes scripts for:</p>
<ul>
<li><p>Getting data from a standard resource</p></li>
<li><p>Running a series of stylised models of IMR against time</p></li>
<li><p>Producing single parameter summaries of sex and country-specific differences in overall trends</p></li>
<li><p>Comparing between different model specifications and trying to find the right balance between model complexity and model accuracy</p></li>
<li><p>Producing model predictions and plotting these against observed values.</p></li>
</ul>
<p>The model specifications considered are not the only models worth considering, and the ‘best’ model presented, model 4, stylises the post 2012 effect in ways that are not especially realistic. However it does allow single summary estimates of differences both prior and post 2012 between countries, and the general strategy can be adapted to other countries and datasets.</p>
<section id="not-covered" class="level3">
<h3 class="anchored" data-anchor-id="not-covered">Not covered</h3>
<ul>
<li><p>Other ways of comparing model fit (e.g.&nbsp;RMSE)</p></li>
<li><p>Negative binomial modelling (largely the same specification, but may produce more plausible confidence intervals</p></li>
</ul>
</section>
</section>
<section id="appendix-downloading-directly-from-hmd" class="level2">
<h2 class="anchored" data-anchor-id="appendix-downloading-directly-from-hmd">Appendix: Downloading directly from HMD</h2>
<p>The first script downloads directly from the Human Mortality Database.</p>
<p>This requires both registering with the HMD, adding username and password as environment variables to R, and also a lot of luck. To try this out do the following:</p>
<ol type="1">
<li>Register with the Human Mortality Database at https://mortality.org. Make sure to record username and password</li>
<li>Within R, and within the console, set the environment variables as follows:</li>
</ol>
<pre><code>Sys.setenv(HMD_USERNAME = "&lt;WHATEVER YOUR USERNAME IS&gt;")
Sys.setenv(HMD_PASSWORD = "&lt;WHATEVER YOUR PASSWORD IS&gt;")</code></pre>
<p>To test that the environment variables have been set correctly</p>
<pre><code>Sys.getenv("HMD_USERNAME") # Should return username
Sys.getenv("HMD_PASSWORD") # Should return password</code></pre>
<p>If these are set correctly, then the first chunk of code <em>should</em> work</p>
<ol start="3" type="1">
<li>To try this in practice, make sure to change <code>eval=false</code> to <code>eval=true</code> in this first chunk</li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>